# Generated by Django 5.1 on 2024-08-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_products_image_products_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
    ]
