# Generated by Django 5.1 on 2024-08-21 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_products_description_promotionproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionproducts',
            name='category',
        ),
        migrations.AddField(
            model_name='promotionproducts',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.products'),
        ),
    ]
