# Generated by Django 5.1 on 2024-08-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_promotionproducts_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionproducts',
            name='product',
        ),
    ]
